# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77af31fbf44bd0ba4fffff4adc5b92f6eb76cc029cdb4809beb839c01df586827d04cd6e00c8162e43295c90437be377f7e7f293d4d67ba71685534194b51fda

test:
  secret_key_base: 57ffb57c9350a383d421e5ba5da92c68f43c624b26b97a6e98989c424ae3cbde947e193b9b72d78762aa9db29d6d0995be02be847faac82f32df4683f985fa93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
